<a href="https://colab.research.google.com/github/bigbirdjones/laguardia_data_analytics/blob/main/NYC_Cooling_Tower_System_Inspection_Results_EDA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Step 1: LOAD DATA

In [2]:
import pandas as pd
# I'll load the data via API in 3 segaments then concatinate to create my full DataFrame.

In [14]:
URL = "https://data.cityofnewyork.us/resource/f9wb-g8mb.csv?$limit=50000"

df1 = pd.read_csv(URL)

/tmp/ipykernel_12343/2484009375.py:3: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df1 = pd.read_csv(URL)

In [15]:
URL = "https://data.cityofnewyork.us/resource/f9wb-g8mb.csv?$limit=50000&$offset=50000"

df2 = pd.read_csv(URL)

In [19]:
URL = "https://data.cityofnewyork.us/resource/f9wb-g8mb.csv?$limit=22000&$offset=100000"

df3 = pd.read_csv(URL)

In [25]:
full_df = pd.concat([df1, df2, df3])
full_df

,bin,system_id,address,borough,zip_code,status,active_equip,inspection_date,violation_code,law_section,...,citation_text,summons_number,inspection_type,bbl,latitude,longitude,community_board,council_district,census_tract,nta_code
0,1015834,2000000122,1271 BROADWAY,Manhattan,10001,Inactive,0,2021-05-21T00:00:00.000,AH8U,24 RCNY §8-05(f)(5),...,NaN,196816281.0,Non-Cycle,1008330078,40.748260,-73.988491,105.0,3.0,7600.0,MN0501
1,1015834,2000000122,1271 BROADWAY,Manhattan,10001,Inactive,0,2021-05-21T00:00:00.000,AH8C,24 RCNY §8-04(a),...,Respondent is in violation of 24 RCNY 8-04(a)(...,881249959.0,Cycle,1008330078,40.748260,-73.988491,105.0,3.0,7600.0,MN0501
2,1015834,2000000122,1271 BROADWAY,Manhattan,10001,Inactive,0,2021-05-21T00:00:00.000,AH8D,24 RCNY §8-04(b),...,Compliance inspections must be completed by a ...,881249968.0,Cycle,1008330078,40.748260,-73.988491,105.0,3.0,7600.0,MN0501
3,1015834,2000000122,1271 BROADWAY,Manhattan,10001,Inactive,0,2021-05-21T00:00:00.000,AH8E,24 RCNY §8-04(c),...,"At the time of inspection, operational records...",NaN,Cycle,1008330078,40.748260,-73.988491,105.0,3.0,7600.0,MN0501
4,1015834,2000000122,1271 BROADWAY,Manhattan,10001,Inactive,0,2021-05-21T00:00:00.000,AH8L,24 RCNY §8-05(c)(3),...,"At the time of inspection, upon Inspector's re...",881249977.0,Cycle,1008330078,40.748260,-73.988491,105.0,3.0,7600.0,MN0501
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21982,1003224,2000002652,227 MADISON ST,Manhattan,10002,Active,3,2025-09-16T00:00:00.000,NaN,NaN,...,NaN,NaN,Cycle,1002700032,40.712777,-73.988417,103.0,1.0,600.0,MN0301
21983,3257059,2000003820,140A 58TH ST,Brooklyn,11220,Active,2,2025-09-16T00:00:00.000,NaN,NaN,...,NaN,NaN,Cycle,3057780001,40.645199,-74.027196,7.0,38.0,1804.0,BK0702
21984,3397939,2000010114,599 WINTHROP STREET,Brooklyn,11203,Active,1,2025-09-16T00:00:00.000,NaN,NaN,...,NaN,NaN,Cycle,3048120001,40.658110,-73.940913,NaN,NaN,80800.0,BK0902
21985,3397939,2000010115,599 WINTHROP STREET,Brooklyn,11203,Active,1,2025-09-16T00:00:00.000,NaN,NaN,...,NaN,NaN,Cycle,3048120001,40.658110,-73.940913,NaN,NaN,80800.0,BK0902
21986,1037988,2000015839,885 2ND AVE,Manhattan,10017,Active,1,2025-09-16T00:00:00.000,NaN,NaN,...,NaN,NaN,Cycle,1013210022,40.753187,-73.969757,106.0,4.0,9000.0,MN0604

#Step 2: CLEAN DATA

In [31]:
full_df['violation_code'].isnull().sum()

np.int64(33782)

In [33]:
full_df.dropna(subset="violation_code")

,bin,system_id,address,borough,zip_code,status,active_equip,inspection_date,violation_code,law_section,...,citation_text,summons_number,inspection_type,bbl,latitude,longitude,community_board,council_district,census_tract,nta_code
0,1015834,2000000122,1271 BROADWAY,Manhattan,10001,Inactive,0,2021-05-21T00:00:00.000,AH8U,24 RCNY §8-05(f)(5),...,NaN,196816281.0,Non-Cycle,1008330078,40.748260,-73.988491,105.0,3.0,7600.0,MN0501
1,1015834,2000000122,1271 BROADWAY,Manhattan,10001,Inactive,0,2021-05-21T00:00:00.000,AH8C,24 RCNY §8-04(a),...,Respondent is in violation of 24 RCNY 8-04(a)(...,881249959.0,Cycle,1008330078,40.748260,-73.988491,105.0,3.0,7600.0,MN0501
2,1015834,2000000122,1271 BROADWAY,Manhattan,10001,Inactive,0,2021-05-21T00:00:00.000,AH8D,24 RCNY §8-04(b),...,Compliance inspections must be completed by a ...,881249968.0,Cycle,1008330078,40.748260,-73.988491,105.0,3.0,7600.0,MN0501
3,1015834,2000000122,1271 BROADWAY,Manhattan,10001,Inactive,0,2021-05-21T00:00:00.000,AH8E,24 RCNY §8-04(c),...,"At the time of inspection, operational records...",NaN,Cycle,1008330078,40.748260,-73.988491,105.0,3.0,7600.0,MN0501
4,1015834,2000000122,1271 BROADWAY,Manhattan,10001,Inactive,0,2021-05-21T00:00:00.000,AH8L,24 RCNY §8-05(c)(3),...,"At the time of inspection, upon Inspector's re...",881249977.0,Cycle,1008330078,40.748260,-73.988491,105.0,3.0,7600.0,MN0501
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21956,3000417,2000014447,1 BOERUM PL,Brooklyn,11201,Active,2,2025-09-22T00:00:00.000,AH8W,24 RCNY §8-06(b)(1),...,"At the time of inspection, 2025 startup cleani...",881327224.0,Cycle,3001530003,40.691955,-73.989059,302.0,33.0,3700.0,BK0202
21957,3137303,2000014383,4813 9TH AVE,Brooklyn,11220,Active,2,2025-09-19T00:00:00.000,AH8S,24 RCNY §8-05(f)(3),...,"At the time of inspection,respondent failed to...",881327242.0,Cycle,3056310001,40.640634,-74.000605,312.0,38.0,11400.0,BK1201
21963,1079184,2000015836,261 11TH AVE,Manhattan,10001,Active,1,2025-09-18T00:00:00.000,AH8X,24 RCNY §8-06(b)(2),...,"At the time of inspection, Respondent failed t...",881327160.0,Cycle,1006730001,40.751495,-74.005118,104.0,3.0,9902.0,MN0401
21979,1000867,2000011115,32 OLD SLIP,Manhattan,10005,Active,2,2025-09-16T00:00:00.000,AH8U,24 RCNY §8-05(f)(5),...,"At the time of inspection, operational records...",881327215.0,Cycle,1000350001,40.703566,-74.008036,101.0,1.0,700.0,MN0101
21981,2003301,2000002765,1181 NELSON AVE,Bronx,10452,Active,1,2025-09-16T00:00:00.000,AH8F,24 RCNY §8-04(d),...,The cooling tower system must be cleaned at le...,881327233.0,Cycle,2025160051,40.837333,-73.926078,NaN,NaN,19900.0,BX0402

In [35]:
print(121987-33782)

88205